### ISSUE TITLE
Is entree compatible with CAN FD ?

### ISSUE THREAD

**Issue by GreyXor** [tuna-f1sh/entree#2]
Hello,
I was wondering if Entree support CAN FD ?
Thanks

**Comment by tuna-f1sh** [comment]
No it only supports CAN since it uses the STM32F042, which does not support CAN FD. You'll need a board with a STM32G0 or one of the products listed in [this document](https://www.st.com/resource/en/application_note/dm00625700-fdcan-peripheral-on-stm32-devices-stmicroelectronics.pdf).

[candleLight_fw](https://github.com/candle-usb/candleLight_fw) lists some but I have no experience with them.
